export const effectors: string[] = [
  "ビーフジョッキー",
  "Taxtixal CRAZY KID",
  "Megacyclops",
  "～PH～XUASΞ",
  "Genuine CRAZY KID as ”Child M”",
  "Diabolos CRAZY KID",
  "ΣtherØØ",
  "～PH～Syndrome...?",
  "Temperance CRAZY KID",
  "TEK-風瑠人-RHYTHM",
  "粛清の cosMo × Method × ～PH～",
  "～PH～rogressive CRAZY KID",
  "PHQUASE phantom",
  "PHQUASE Utopia",
  "深淵の闇より出でし光芒を描く者～PH～",
  "MAD CHILD Dystiopia",
  "Captain CRAZY KID",
  "クリムゾンホットテンペスト・改",
  "PHQUASE Lūcifer",
  "MAD CHILD & Hirayasu Matsudo",
  "RED MAD HOT CHILDREN",
  "クリムゾンホットテンペスト＆クリスタルコールドブリザード",
  "TEK-風瑠人",
  "MAD CHILD",
  "Ether99",
  "TEK-A-RHYTHM-IX Ｘ クリムゾンホットテンペスト",
  "風瑠人",
  "電撃ロブスター",
  "Royα∠ CrαckEr",
  "クリムゾンホットテンペスト",
  "SALμON GRAPHY",
  "クリムゾンホットテンペスト (supervised by Bahamūt)",
  "～PH～ prebirth",
  "鋼鐵のビスカチア",
  "レッドホットスクリューズ No.24",
  "MAD CHILD ver.VI",
  "ZangY Bros.",
  "月刊ミズタニ",
  "２κονノックオン",
  "松田博泰・超希想箋楽隊",
  "～PH～ the Valhalla",
  "cosMo＠暴走P",
  "-",
  "赤熱螺旋",
  "MAD CHILD vs. 風瑠人",
  "フォックスロット",
  "ビーフジョッ竹",
  "サイバーガスタンク",
  "七色メットスクリューズ",
  "SALMON GASTANK",
  "The Hirayasu Matsudo",
  "亡国の電撃ロブスター",
  "レッドホットスクリューズ×～PH～",
  "ごましお風",
  "Akizuki NagoΛΛu♪",
  "†:凹ーダー凸ード:†",
  "Amazeki Kagome & Akizuki Nagomu",
  "Akizuki Nagomu 2nd Ignition",
  "cosMo凸暴走P",
  "G線上のロブスター",
  "～PHPHPH～",
  "クリムゾンホットテンペスト ＸＸ TEK-A-RHYTHM-IX",
  "θcosMoθ暴走Pθ",
  "零色メソッド",
  "浮世魔神(黒)",
  "テカタニ feat. テカタニ",
  "TEK-A-RHYTHM-IX",
  "七色Method Infrared",
  "時間軸を超越する者～PH～",
  "NET-i-TEK",
  "Megacycle",
  "MAD CHILD meets レッドホットスクリューズ",
  "TEK-A-RHYTHM",
  "SCライオット",
  "蒼穹の電撃ロブスター",
  "cosMo@暴走P",
  "Akizuki Nagomu since20121125",
  "レッドホットスクリューズ",
  "SOUND VOLTEX Effectors",
  "MAD CHILD VX",
  "PHQUASE",
  "凹ーダー凸ード",
  "Beat Professor Maxima",
  "dj strachen",
  "CosΣo＠暴走P",
  "ごましおくんの姉",
  "七色Method extended by SHOUTICE",
  "Voltex master？@.424kHz",
  "浮世ドゥーン×TEK-A-TSUTHM",
  "ごましお@暴走P",
  "MAD CHILD Ressurection",
  "月刊風瑠タニ",
  "PHQUASE forever",
  "MAD CHILD the Execute",
  "PHQUASE the Exceed",
  "PHQUASE rebirth",
  "SC(バイオメトリクス+ライオット)",
  "月刊ごましお☆グッチーニ",
  "ダークダークダーク",
  "七色Method",
  "ダークダーク",
  "レッドホットビーフ＆スクリュージョッキー",
  "POT-E-RHYTHM",
  "PHQUASE since20131221",
  "レッドホットスクリューズ×TEK-A-RHYTHM",
  "フル＋テカ＋マコ",
  "Guccini＠暴走PG",
  "月刊ポテしおユカリ♣club",
  "MAD CHILD Nightmare",
  "PHQUASE ver.II vs. PHQUASE ver.III",
  "TEK-A-RETURNS",
  "SALMON GRAPHY",
  "Undisclosed Hard Groove",
  "ポテト亀山",
  "Probably Finest Dee One",
  "ロイヤルクラッカー",
  "唐揚Brother + Ginza-Sis",
  "鋼のビスカッチャ",
  "kamuy noko",
  "FriedChickenSisters",
  "Akizuki Nagomu",
  "Antonio Guccini",
  "Hermit♣club",
  "CRAIG AKAGI",
  "Hirayasu Matsudo",
  "レッドホットポテト",
  "SALMON GRAPHY×電撃ロブスター",
  "鋼のビスカッチャ×電撃ロブスター",
  "おすし仮面♣",
  "burning in ～PH～ell",
  "NOX",
  "#Namescapes",
  "Perfect Ultimate CRAIG!!",
  "Puni Puni ロブスター",
  "こすも８ｂｉｔ",
  "電撃ロブスター＆ロイヤルクラッカー",
  "1+1/2conノックオン",
  "ZANGI Sisterss",
  "IIconノックオン",
  "An East Scarlet",
  "カオスのビスカッチャ",
  "レッドホットビーフ&スクリュージョッキーズ",
  "MAD CHILD×Hirayasu Matsudo×MAD CHILD",
  "サイバーガスタンク×鋼のビスカッチャ",
  "レッドホットスクリューズと～PH～",
  "ところがどっこい鑑定団",
  "ばーフジョッキー!!!!",
  "ビープジョッキー",
  "ブルーコールドビーフ＆ハリケーンジョッキーズ",
  "A～PH～oy!!",
  "さあ超えていこう、この音で～PH～",
  "井ハッシュド鑑定団",
  "レッドホットビーフ＆スクリュージョッキーズ",
  "MADホットスクリューズ",
  "からあげブラザー市場",
  "ブルーコールドハリケーンズ",
  "kamuy noko include",
  "Verdefo",
  "金色の夜叉",
  "Jin Majima",
  "楊 麗華",
  "EIVY",
  "Akizuki Nagomu implemented by SDVX Effectors",
  "DeNGeKiLoWBooSteR",
  "cosMo＠暴走P×電撃ロブスター",
  "浮世マシーン",
  "兄ジェットマン",
  "SHiJiMiSo Soup.☆彡",
  "ビーフジョッ9",
  "MaKoTo",
  "蒼弐 feat.RASIS -BOOTH- forever",
  "スエヒロ",
  "電撃ロブスターDeluxe",
  "～PH～ごましおくん",
  "Hirayasu Matsudo & MAD CHILD",
  "東京ブルトゥーム",
  "ダークダークダークダーク",
  "apple kong",
  "電撃ロブニャン",
  "大名マシーン vs. しばまる子",
  "Akizuki Nagomu+フォックスロット",
  "cosMo×電撃ロブスター×サイバーガスタンク",
  "びすかっちゃ　と　ろぶすたー",
  "Megacycle respect for M.M.M.",
  "MAD CHILD & Megacycle",
  "電撃+ロブスター",
  "TEK-A-RHYTHM vs. 逆球レジェンド",
  "νοχ",
  "はがねのびすかっちゃ",
  "SCバイオメトリクス",
  "怪人・狂気児童",
  "トルネードボーイ",
  "びーフジョッキー",
  "歩手登と美津多仁",
  "Amazeki Kagome",
  "天空の電撃ロブスター",
  "Megacycle Vs. Megaheartz",
  "cosMo＠うさぎ愛好会",
  ".424kHz",
  "闇黒のEIVY",
  "ブルーコールドハリケーンズ vs. レッドホットスクリューズ",
  "United Effectors",
  "Chapter 04「神秘」",
  "DJ みさこ",
  "月刊ミズタニ(戦士)",
  "MAD CHILD & Bob Shimantogawa",
  "レッドホットスクリューズ + ブルーコールドハリケーンズ",
  "風瑠マシーン",
  "逆球レジェンド",
  "からあげブラザーズ vs. MAD CHILD",
  "MaKoTo仮面",
  "MAD CHILD VS Megacycle",
  "Re:Antonio Guccini",
  "BEMANI Sound Team ''TAG'' supported by SCライオット",
  "ポテトマシーン",
  "ウィーアーライジング！！～PH～",
  "tEK-A-RHYTHM",
  "SUPER SUMMER SHIMANTOGAWA",
  "THE THIRD MAN",
  "ブルーコールドハリケーンズ＆レッドホットスクリューズ",
  "ごましおくん vs. PHQUASE",
  "Z",
  "レッドホットミズタニ",
  "浮世チュニーン",
  "大日本松倶楽部",
  "cosMo＠暴走PSYCHOPATH",
  "からあげ//シスターズ",
  "TEK-A-TSUTHM",
  "月刊ポテタニ",
  "キーワード「ネコ　動画」～PH～",
  "レッドホットビスケット",
  "喜屋武ミカエル",
  "SCライオット from SOUND VOLTEX譜面ボーイズの逆襲",
  "ねちっこく堂",
  "Ester運動",
  "水金地火木土天海冥 冥 冥 冥 冥 めめっめめめっ 四万十川",
  "せ～のッ！～PH～",
  "Sammy/A",
  "バイラルフラッシャー",
  "びーふジョッキーだよ☆ＢＪＫ",
  "OMGライオット from SOUND VOLTEX譜面ボーイズ",
  "NEO GUCCINI",
  "TEK-A meets RHYTHM",
  "PHQUASE vs. FUKASE",
  "ビー フジョッキー",
  "Hermit♣ミズタニ",
  "TEK-A-マシーン",
  "Hirayasu Matsudo × ごましおくん",
  "レッドホットスクリューズ vs. ブルーコールドハリケーンズ",
  "逆球レジェンド vs. しばまる子",
  "Hermit♠レジェンド",
  "PHQUASE Hēlios",
  "MAD CHILD Hyperīōn",
  "浮世コスーン",
  "ユカリ☆chan vs. レッドホットスクリューズ",
  "レッドホットスクリューズ♥TEK-A-RHYTHM",
  "こんなミズタニありえなーーい!!",
  "七色Method 1+1/2",
  "TAKUYA",
  "PHQUASE VS 深瀬",
  "ビーフージョッキー",
  "#Hirayasu_Matsudo_dancing_in_the_world",
  "七色Method++",
  "すーぱーサンダー☆ボブ美ちゃん",
  "ナカ田サトル",
  "ムーニャポヨポヨデンゲキロブスター",
  "PF reconciliation",
  "Mech-Megacycle",
  "ごましおくん vs. DJ摂津 vs. PHQUASE",
  "SHOUTICE",
  "月刊TAKUYA",
  "dj paq-poq",
  "P.H.Q.",
  "DJ 摂津 feat. ごましおくん",
  "TEK-A-RHYTHM×月刊ミズタニ",
  "仏蘭西 和蘭陀 西蔵 京都 倫敦 露西亜 四万十川",
  "月刊ミズタニとTEK-A-RHYTHM",
  "PHQUASE since20121125",
  "MAD CHILD vs Megacycle",
  "dj strassen",
  "フォックスロット feat. Amazeki Kagome",
  "strassen",
  "2conノックオン",
  "からあげブラザーズ",
  "Secret Lv.09",
  "能天気 ぐるぐる ～PH～ 頭 ガチガチ",
  "サイバーマッスルガスタンク",
  "ZANGI Bros.",
  "↑↑↓↓←→←→PH",
  "鋼のビスカッチャ×サイバーガスタンク",
  "名誉グレイス王国民",
  "元祖レイシス親衛隊長",
  "B∞フジョッキー",
  "七色Chocolatière",
  "おつまみロブスター",
  "Hirayasu Matsudo (MAD CHILD Remix)",
  "おやすみなさい。",
  "ディープブルーコールドハリケーンズ（respect HM）",
  "電撃ロブスター×cosMo@暴走P",
  "レッドホット+スクリューズ",
  "フォックスロット & kamuy noko",
  "～PH～ ver.V",
  "cosMo＠暴走Pの消失",
  "ヒーフジョッキー",
  "ボルテ学園美術部",
  "ベビーフジョッキー",
  "からあげブラザーズ(レモン派)",
  "ドッタンバッタン～PH～",
  "DJ みさこ vs. 楊 麗華",
  "レッドロックスクリューズ",
  "秋月なごむ",
  "ひとくちMethod",
  "azuma",
  "Jessica Toshimitsu",
  "おからヒット　タイプD",
  "MAD CHILD, the Arcade Prisoner",
  "Hiroyasu Matsuda",
  "BATAASHI",
  "ふかせ",
  "浮世×マシーン",
  "おすし仮面",
  "Satchy",
  "ユカリ☆chan vs. 月刊ミズタニ",
  "おすし♣club",
  "I'm alive～PH～",
  "SCイノセンス",
  "CRAIG AKAGI vs. 凹ーダー凸ード",
  "GOLD",
  "蒼弐 ver.IV",
  "星空を翔ける～CA～",
  "レッドホットスロォモォション",
  "MaKoTo & マシーン",
  "電撃ロブスター(エフェクター忍者)",
  "夢と希望のカタマリ～PH～",
  "憂夜マシーン",
  "月刊ユカタニ",
  "Antonio+Guccini",
  "ひとくちピエロ",
  "狂風少年鑑定団",
  "ふわふわユカタニ",
  "グッチーニ(SSL)",
  "Ester44",
  "月刊ミズタニ × 逆球レジェンド × ユカリ☆chan",
  "WMM-E",
  "TAG supported by SCライオット",
  "MAD CHILD & Hiroyasu Matsuda",
  "M.M.M.M.M.M.M.",
  "MAD CHILD + Megacycle",
  "SCバイオメトリクスR",
  "Yu-tomo",
  "月刊ミズタニ × Hermit♣club",
  "ねちマシーン",
  "†PHQUASE†",
  "ユカリ♣ポテト",
  "スカイシュート",
  "レッドホットスクリューズ♠TEK-A-RHYTHM",
  "IIDXで九段受かれないSCバイオメトリクス",
  "MAK-O-RHYTHM",
  "Padcontrollers",
  "でひゃいましゅぅぅぅ～～っっ！！！ふかせ",
  "ボブ☆四万十川のパーフェクトダンス教室",
  "月刊ミズタニS",
  "ほおずき程度には赤いYUK-A-RHYTHM",
  "月刊バイオメトリクス",
  "SCミズタニ",
  "凹ーダー凸ー堂",
  "PHQUASE vs. MAD CHILD",
  "SCバイオメトリクス Vs. 金色の夜叉 feat. 忍",
  "MADしばまるCHILD",
  "Megaまる子",
  "Megacyclone",
  "狂気のふかせ",
  "TEK-A-リ☆chan",
  "しばまる子 vs. TEK-A-RHYTHM",
  "Sammy/A rejected by 赤バステルくん",
  "Megacycle & MAD CHILD",
  "がんばれ!!ミズしおくん",
  "コーヒーブレイカー",
  "Bob Shimantogawa",
  "しばまる子",
  "ki4ki4",
  "絶食性:ユカしお症候群",
  "R-115Hz",
  "ジグザグレエザア",
  "↑↑↓↓←→←→MC",
  "↑↑↓↓←→←→BSP",
  "↑↑↓↓←→←→DDD",
  "からあげしすたーず",
  "kamuy noko abstract",
  "からあげシスターズ",
  "バター氏",
  "世界をリメイク～PH～",
  "からあげシスターズさんじゅうななさい",
  "一人じゃない～PH～",
  "マッドチャイルド ＆ ひらやすまつど",
  "狂風少年鑑定Soup.☆彡",
  "ちたちゅれ with バタアシ",
  "恵方真紀",
  "おからヒット",
  "バタアシ",
  "影符",
  "cosMo＠暴走Beast",
  "Fortunality",
  "おすし仮面（ポテト）",
  "cosMo＠暴走ぱあ",
  "MAD CHILD powerd by 宣伝部の田中さん",
  "ユカリ☆chan",
  "PHQUASE STARLiGHT",
  "金色のSC夜叉トリクス",
  "DJ 摂津",
  "ユカリ & MaKoTo",
  "Low of cosines",
  "ユカリ♣club",
  "DJ 摂津 × メルシー岡田",
  "博多の男",
  "SUPER EFFECTOR 努-TSUTOMU-",
  "Law of cosines",
  "MAD CHILD ver.III 1st SEASON",
  "わかば",
  "MaKoToレジェンド",
  "ユカリ☆ごましお",
  "浮世まる子",
  "Hermit♣club vs. 逆球レジェンド",
  "浮世♣マシーン",
  "レッドホットスクリューズ × Megacycle",
  "DJ WILDPARTY",
  "ユカリの男",
  "TEK-A-RHYTHM × ごましおくん",
  "もう一貫も食べれな～い！ふかせ",
  "1+1+1は3じゃないぞ。オレたちは1+1+1でメガ松茶だ。⑨倍だぞ⑨倍",
  "週刊ミズタニンニク",
  "TEK-A-RHYTHM×しばまる子",
  "マッドチャイルド＆ひらやすまつど",
  "ひとくちパンダ",
  "MaKoTo & ポテト",
  "P1Y02",
  "Law of cosines vs. TAKUYA",
  "イエローSUB魔鈴 × TAKUYA",
  "カジキガツオ",
  "逆球レジェンド × MISY.b",
  "Princess みさこ",
  "PHUQUASE ver.I",
  "月刊ミズタニ ver.II",
  "ごましおくん",
  "ま☆",
  "地方創生☆フカセクティクス",
  "MISY.b",
  "G9D",
  "イエローSUB魔鈴",
  "週刊ミズタニ",
  "ごましおくん vs. Megacycle",
  "MAD CHILD & Fortunality",
  "もう勉強したくない！ふかせ",
  "THE THIRD MAN said ''I'm not MAD CHILD''.",
  "mitsu",
  "まだまだ負けないんだから～☆ki4ki4",
  "DJ UTO",
  "Acid=Stone Valley",
  "kinoto",
  "ごましおくん(ニーソックス！)",
  "あおにさい",
  "PHQUASE×レッドホットスクリューズ",
  "月刊ミズタニ/A",
  "レッドホットスクリューズ×PHQUASE",
  "Megacycle×しばまる子",
  "漂白太郎",
  "中仙道マーゴット",
  "SDVXエフェクト取締法違反の容疑でエフェクターの男を逮捕しました",
  "七色Method feat. 影符",
  "TAKUYA × MaKoTo",
  "MAD CHILD vs. Hirayasu Matsudo",
  "U.N. Okawatt",
  "みさこ",
  "''揚げ物ディスコ事件''対策本部",
  "ごましお風ミズタニ",
  "PHQUASE×逆球レジェンド",
  "ブラックとちおとめ♪(｀・ω・´)",
];
